### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sabina-cognite**
Can I add a demo notebook to this repo, it is intended for Chevron to get access to it together with API documentation in the same repo.

### CODE REVIEW

**Comment by soleh23** [comment]
@sabina-cognite I don't think it's a good idea to have jupyter notebook in this repository. As for the seismic api it's public, you just need to share the link, however that api doc is intended for developers, the docs for clients/sdk users are being developed.

**Comment by sabina-cognite** [comment]
the reason I wanted it here - it is the only public seismic repo. Anders did something and I have the file access thru this link: https://raw.githubusercontent.com/cognitedata/seismic-proto/sabina-cognite-patch-1/Demo_SeismicAPI_PGS.ipynb

**Comment by soleh23** [comment]
> the reason I wanted it here - it is the only public seismic repo. Anders did something and I have the file access thru this link: https://raw.githubusercontent.com/cognitedata/seismic-proto/sabina-cognite-patch-1/Demo_SeismicAPI_PGS.ipynb

should we consider it done then?

**Comment by amorken** [comment]
I didn't actually do anything, that particular URL does not require a PR to be posted. It's provided by GitHub, as long as there's a branch called "sabina-cognite-patch-1" in this repository, containing that particularfile.

**Comment by sabina-cognite** [comment]
Please leave it as it is for now, after the meeting this afternoon, we can set it to done

**Pull request closed without merging**
