### PR TITLE
External id on survey

### PR DESCRIPTION
**Pull request by BenChand**

### CODE REVIEW

**Review by amorken — APPROVED** [review]

**Comment by amorken** [comment]
Hmm. Maybe also check the v1 survey APIs in seismic_service_messages.proto?

**Comment by BenChand** [comment]
I think it just uses the v0 type

**Comment by BenChand** [comment]
Actually i think you're right, there's a `SurveyWithFiles` type that needs updating

**Comment by audunska** [comment]
Would be nice to get this merged so I can build my PR :smile:

**Pull request merged**
