### PR TITLE
Fix: Seismic store IDs in CreateSeismicRequest is also int64

### PR DESCRIPTION
**Pull request by skairunner**

### CODE REVIEW

**Review by MariuszCognite — COMMENTED** [review]
hmmm, shouldn't it be uint64?

**Comment by skairunner** [comment]
> hmmm, shouldn't it be uint64?

I believe the current schema uses int64s, so it's technically correct to use i64 even if practically all IDs are u64s

**Review by MariuszCognite — APPROVED** [review]

**Comment by amorken** [comment]
> > hmmm, shouldn't it be uint64?
> 
> I believe the current schema uses BIGINT, so it's technically correct to use i64 even if practically all IDs are u64s

The Cognite APIs in general use numbers between 10**9 and 2*'53, so any int with 53 non-sign bits should be fine. int54!

**Comment by TerjeWiigMathisen** [comment]
This sounds a lot like it was designed to work inside a double fp variable,
i.e. 1:11:52 so you can store 53-bit signed ints without any
rounding/truncation.

**Pull request merged**
