### PR TITLE
SBS-1389 external_id for survey and files

### PR DESCRIPTION
**Pull request by BenChand**

### CODE REVIEW

**Review by skairunner — COMMENTED** [review]
I wonder why the specific ExternalId type when it's simply wrapping a string? I feel like it would be fine not to have that additional wrapper layer, especially since empty external ids tend to be illegal anyways.

**Comment by audunska** [comment]
> I wonder why the specific ExternalId type when it's simply wrapping a string? I feel like it would be fine not to have that additional wrapper layer, especially since empty external ids tend to be illegal anyways.

It does help in documenting parameters, and keep us from mixing up different kinds of identifiers..

**Comment by skairunner** [comment]
That's fair, but the downside is yet another annoying type to have to unwrap in Protobuf :(

**Comment by amorken** [comment]
https://docs.cognite.com/api/v1/#operation/updateAssets - the assets API, as well as timeseries, files, events and maybe others, I haven't checked, allow updating or removing the externalId in update calls. I think we should match the behavior of the rest of CDF.

**Review by amorken — APPROVED** [review]

**Pull request merged**
