### PR TITLE
Use github actions

### PR DESCRIPTION
**Pull request by BenChand**
Public repos now need to use github actions instead of jenkins ci/cd

### CODE REVIEW

**Comment by BenChand** [comment]
An admin for this repo will need to remove the continuous integration requirement from jenkins so this can be merged

**Review by amorken — APPROVED** [review]
:pray: 

This is great! I was looking at this myself, but you beat me to it. =)

**Comment by amorken** [comment]
(I have changed the branch protection rules now.)

**Comment by BenChand** [comment]
Thanks!

**Pull request merged**
