### PR TITLE
Add last_modified to v1 search endpoints

### PR DESCRIPTION
**Pull request by skairunner**
Right now I've added it as, essentially, an AND clause to every search.

If we think there isn't a use case for filter specificity, it would be simpler to only allow searching by one of (identifier, last_modified). Opinions would be appreciated

### CODE REVIEW

**Review by audunska — COMMENTED** [review]
I think an `and` filter is perfectly appropriate. But I wonder if it could go into the `SearchSpec` instead? Then it would automatically exclude other filters (except in SearchSurvey), keeping the code simple.

**Comment by skairunner** [comment]
If it's part of SearchSpec, then you could *either* search by one of the other criteria, *or* search by last modified. I don't think you can do both. So if we want it to be an AND filter it would have to be outside of the searchspecs.

**Comment by audunska** [comment]
Yes, so that would enable the typical use-case of listing everything that changed recently, and explicitly disallow other use-cases. Also would keep the code simpler. Worth considering, but maybe too limiting?

**Comment by skairunner** [comment]
Hmm. I think it's probably fine to not overcomplicate it and go ahead and limit it like that.

**Review by audunska — APPROVED** [review]
Right, putting it in the search spec is maybe not the most helpful, since then you'll be searching by last modified date on other objects. Lots of tradeoffs here! I think this one is a good one.

**Pull request merged**
